// Package protos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package protos

// CreatedRoomRequest defines model for CreatedRoomRequest.
type CreatedRoomRequest struct {
	// Name Room master's name
	Name string `json:"name"`
}

// CreatedRoomResponse defines model for CreatedRoomResponse.
type CreatedRoomResponse struct {
	// Id Room ID
	Id *string `json:"id,omitempty"`

	// Users Array of users in the room
	Users *[]User `json:"users,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// JoinRoomRequest defines model for JoinRoomRequest.
type JoinRoomRequest struct {
	// Name Name to use when joining the room
	Name string `json:"name"`
}

// JoinedRoomResponse defines model for JoinedRoomResponse.
type JoinedRoomResponse struct {
	// Id Room ID
	Id *string `json:"id,omitempty"`

	// Timestamp Timestamp of when the user joined
	Timestamp *int64 `json:"timestamp,omitempty"`

	// Users Array of users in the room
	Users *[]User `json:"users,omitempty"`
}

// User defines model for User.
type User struct {
	// Avatar User avatar URL
	Avatar *string `json:"avatar,omitempty"`

	// Balance User balance (can be negative)
	Balance *int32 `json:"balance,omitempty"`

	// Id User ID
	Id *string `json:"id,omitempty"`

	// Name User name
	Name *string `json:"name,omitempty"`
}

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = CreatedRoomRequest

// JoinRoomJSONRequestBody defines body for JoinRoom for application/json ContentType.
type JoinRoomJSONRequestBody = JoinRoomRequest
