// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: room.proto

package roompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // page cursor code
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequest) Reset() {
	*x = RoomListRequest{}
	mi := &file_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequest) ProtoMessage() {}

func (x *RoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequest.ProtoReflect.Descriptor instead.
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *RoomListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RoomListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RoomListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GetRoomResponse     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResponse) Reset() {
	*x = RoomListResponse{}
	mi := &file_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResponse) ProtoMessage() {}

func (x *RoomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResponse.ProtoReflect.Descriptor instead.
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomListResponse) GetData() []*GetRoomResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreatedRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string name = 2;  // room master the name
	UserId        string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"` // user the machine code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedRoomRequest) Reset() {
	*x = CreatedRoomRequest{}
	mi := &file_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedRoomRequest) ProtoMessage() {}

func (x *CreatedRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedRoomRequest.ProtoReflect.Descriptor instead.
func (*CreatedRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *CreatedRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatedRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // is room id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedRoomResponse) Reset() {
	*x = CreatedRoomResponse{}
	mi := &file_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedRoomResponse) ProtoMessage() {}

func (x *CreatedRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedRoomResponse.ProtoReflect.Descriptor instead.
func (*CreatedRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *CreatedRoomResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// nothing
type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// nothing
type UpdateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoomResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderBookListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookListRequest) Reset() {
	*x = OrderBookListRequest{}
	mi := &file_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookListRequest) ProtoMessage() {}

func (x *OrderBookListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookListRequest.ProtoReflect.Descriptor instead.
func (*OrderBookListRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *OrderBookListRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type OrderBookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Volume        int32                  `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookListResponse) Reset() {
	*x = OrderBookListResponse{}
	mi := &file_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookListResponse) ProtoMessage() {}

func (x *OrderBookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookListResponse.ProtoReflect.Descriptor instead.
func (*OrderBookListResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *OrderBookListResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderBookListResponse) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type ProfitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitRequest) Reset() {
	*x = ProfitRequest{}
	mi := &file_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitRequest) ProtoMessage() {}

func (x *ProfitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitRequest.ProtoReflect.Descriptor instead.
func (*ProfitRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *ProfitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProfitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Profit        float64                `protobuf:"fixed64,2,opt,name=profit,proto3" json:"profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitResponse) Reset() {
	*x = ProfitResponse{}
	mi := &file_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitResponse) ProtoMessage() {}

func (x *ProfitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitResponse.ProtoReflect.Descriptor instead.
func (*ProfitResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *ProfitResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfitResponse) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

type InTheRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InTheRoomRequest) Reset() {
	*x = InTheRoomRequest{}
	mi := &file_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InTheRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InTheRoomRequest) ProtoMessage() {}

func (x *InTheRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InTheRoomRequest.ProtoReflect.Descriptor instead.
func (*InTheRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{12}
}

func (x *InTheRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InTheRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InTheRoom     bool                   `protobuf:"varint,1,opt,name=inTheRoom,proto3" json:"inTheRoom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InTheRoomResponse) Reset() {
	*x = InTheRoomResponse{}
	mi := &file_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InTheRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InTheRoomResponse) ProtoMessage() {}

func (x *InTheRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InTheRoomResponse.ProtoReflect.Descriptor instead.
func (*InTheRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{13}
}

func (x *InTheRoomResponse) GetInTheRoom() bool {
	if x != nil {
		return x.InTheRoom
	}
	return false
}

var File_room_proto protoreflect.FileDescriptor

const file_room_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"room.proto\"(\n" +
	"\x0eGetRoomRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"C\n" +
	"\x0fGetRoomResponse\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\auserIds\x18\x02 \x03(\tR\auserIds\"=\n" +
	"\x0fRoomListRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"8\n" +
	"\x10RoomListResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.GetRoomResponseR\x04data\",\n" +
	"\x12CreatedRoomRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"%\n" +
	"\x13CreatedRoomResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11UpdateRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12UpdateRoomResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x14OrderBookListRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"G\n" +
	"\x15OrderBookListResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\x05R\x06volume\"'\n" +
	"\rProfitRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x0eProfitResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06profit\x18\x02 \x01(\x01R\x06profit\"*\n" +
	"\x10InTheRoomRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x11InTheRoomResponse\x12\x1c\n" +
	"\tinTheRoom\x18\x01 \x01(\bR\tinTheRoom2\xf3\x02\n" +
	"\vRoomService\x12,\n" +
	"\aGetRoom\x12\x0f.GetRoomRequest\x1a\x10.GetRoomResponse\x12+\n" +
	"\x04List\x12\x10.RoomListRequest\x1a\x11.RoomListResponse\x128\n" +
	"\vCreatedRoom\x12\x13.CreatedRoomRequest\x1a\x14.CreatedRoomResponse\x125\n" +
	"\n" +
	"UpdateRoom\x12\x12.UpdateRoomRequest\x1a\x13.UpdateRoomResponse\x129\n" +
	"\tOrderBook\x12\x15.OrderBookListRequest\x1a\x15.OrderBookListRequest\x12)\n" +
	"\x06Profit\x12\x0e.ProfitRequest\x1a\x0f.ProfitResponse\x122\n" +
	"\tInTheRoom\x12\x11.InTheRoomRequest\x1a\x12.InTheRoomResponseBCZAgithub.com/Crows-Storm/scoreboard/internal/common/genproto/roompbb\x06proto3"

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData []byte
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)))
	})
	return file_room_proto_rawDescData
}

var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_room_proto_goTypes = []any{
	(*GetRoomRequest)(nil),        // 0: GetRoomRequest
	(*GetRoomResponse)(nil),       // 1: GetRoomResponse
	(*RoomListRequest)(nil),       // 2: RoomListRequest
	(*RoomListResponse)(nil),      // 3: RoomListResponse
	(*CreatedRoomRequest)(nil),    // 4: CreatedRoomRequest
	(*CreatedRoomResponse)(nil),   // 5: CreatedRoomResponse
	(*UpdateRoomRequest)(nil),     // 6: UpdateRoomRequest
	(*UpdateRoomResponse)(nil),    // 7: UpdateRoomResponse
	(*OrderBookListRequest)(nil),  // 8: OrderBookListRequest
	(*OrderBookListResponse)(nil), // 9: OrderBookListResponse
	(*ProfitRequest)(nil),         // 10: ProfitRequest
	(*ProfitResponse)(nil),        // 11: ProfitResponse
	(*InTheRoomRequest)(nil),      // 12: InTheRoomRequest
	(*InTheRoomResponse)(nil),     // 13: InTheRoomResponse
}
var file_room_proto_depIdxs = []int32{
	1,  // 0: RoomListResponse.data:type_name -> GetRoomResponse
	0,  // 1: RoomService.GetRoom:input_type -> GetRoomRequest
	2,  // 2: RoomService.List:input_type -> RoomListRequest
	4,  // 3: RoomService.CreatedRoom:input_type -> CreatedRoomRequest
	6,  // 4: RoomService.UpdateRoom:input_type -> UpdateRoomRequest
	8,  // 5: RoomService.OrderBook:input_type -> OrderBookListRequest
	10, // 6: RoomService.Profit:input_type -> ProfitRequest
	12, // 7: RoomService.InTheRoom:input_type -> InTheRoomRequest
	1,  // 8: RoomService.GetRoom:output_type -> GetRoomResponse
	3,  // 9: RoomService.List:output_type -> RoomListResponse
	5,  // 10: RoomService.CreatedRoom:output_type -> CreatedRoomResponse
	7,  // 11: RoomService.UpdateRoom:output_type -> UpdateRoomResponse
	8,  // 12: RoomService.OrderBook:output_type -> OrderBookListRequest
	11, // 13: RoomService.Profit:output_type -> ProfitResponse
	13, // 14: RoomService.InTheRoom:output_type -> InTheRoomResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_proto_rawDesc), len(file_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
