// Package protos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package protos

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	User *User `json:"user,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Password User password
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token JWT authentication token
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Avatar User avatar URL (optional)
	Avatar *string `json:"avatar,omitempty"`

	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Name User name
	Name string `json:"name"`

	// Password User password (minimum 6 characters)
	Password string `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// Token JWT authentication token
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// Avatar User avatar URL (optional)
	Avatar *string `json:"avatar,omitempty"`

	// Name User name (optional)
	Name *string `json:"name,omitempty"`

	// Password New password (optional, minimum 6 characters)
	Password *string `json:"password,omitempty"`
}

// UpdateUserResponse defines model for UpdateUserResponse.
type UpdateUserResponse struct {
	User *User `json:"user,omitempty"`
}

// User defines model for User.
type User struct {
	// Avatar User avatar URL
	Avatar *string `json:"avatar,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt *int64 `json:"created_at,omitempty"`

	// Email User email address
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id User ID
	Id *string `json:"id,omitempty"`

	// Name User name
	Name *string `json:"name,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest
